---
title: " R, MySQL and Armchair Analysis"
output: html_notebook
---

```{r}
# install.packages("RMySQL")
library(RMySQL)
help(package = "RMySQL")
```

```{r}
# install.packages("tidyverse")
update.packages()
library(tidyverse)
mydb = dbConnect(MySQL(), user='root', password='', dbname='armchair_analysis', host='localhost')
dbListTables(mydb)
```

```{r}
dbGetQuery(con = mydb,
           "select * from offense where tdret != 0 limit 10")
```

```{r}
# we don't get points for return yards
dbSendQuery(con = mydb,
           "select 
              player
            , gid
            , game
            , seas
            , year
            , team
            , py
            , ints
            , tdp
            , ry
            , rec 
            , tdrec
            , fuml
            from offense") %>%
           fetch() %>%
           View()

dbClearResult(dbListResults(mydb)[[1]])
```

```{r}
# we don't get points for return yards
offense <- dbGetQuery(con = mydb,
           "select 
              a.player
            , b.wk as week
            , a.year
            , a.team
            , 0.04*py + -2*ints + 4*tdp + 0.1*ry + 0.1*recy + 6*tdr + 6*tdrec -2*fuml +6*tdret as fp
            from offense as a
            join game as b on a.gid = b.gid") 
head(offense)
```
```{r}
dbGetQuery(con = mydb,
           "select * from conv limit 10")
```



```{r}
dbGetQuery(con = mydb, "select * from game limit 10")
two_point <- dbGetQuery(con = mydb,
                        "select 
                          a.*
                        , b.gid
                        , c.seas as year
                        , c.wk as week 
                        from conv as a 
                        join play as b on a.pid = b.pid
                        join game as c on b.gid = c.gid where conv = 1")
head(two_point)
rush_two_point <- two_point %>%
  filter(bc != "")
pass_two_point <- two_point %>%
  filter(psr != "")
two_point %>%
  filter(bc == "", psr == "") # forget this one


head(pass_two_point)
head(offense)
offense2 <-
  offense %>%
  left_join(., 
            pass_two_point %>% group_by(week,year,psr) %>% summarise(count = n()), 
            by = c("year","week","player" = "psr")) %>% 
  mutate(fp = ifelse(is.na(count) == FALSE, fp + 2*count, fp)) %>%
  select(-count)
head(offense2)
offense3 <-
  offense2 %>%
  left_join(.,
            pass_two_point %>% group_by(week,year,trg) %>% summarise(count= n()),
            by = c("year","week","player" = "trg")) %>%
  mutate(fp = ifelse(is.na(count) == FALSE, fp+2*count, fp)) %>%
  select(-count)

offense4 <-
  offense3 %>%
  left_join(.,
            rush_two_point %>% group_by(week,year,bc) %>% summarise(count = n()),
            by = c("year","week","player" = "bc")) %>%
  mutate(fp = ifelse(is.na(count) == FALSE, fp+2*count, fp)) %>%
  select(-count)

```  


## Kicking
```{r}
dbGetQuery(con = mydb,
           "select * from fgxp limit 10")
```

```{r}
dbGetQuery(con = mydb,
           "select * from game limit 10")
dbGetQuery(con = mydb,
           "select * from play limit 10")
kicking <- dbGetQuery(con = mydb,
                      "
                      select
                       a.fkicker as player
                      ,b.seas as year
                      ,b.wk as week
                      ,sum(a.pts) as points
                      from
                      (select 
                        a1.pid
                      , b1.gid
                      , a1.fkicker
                      , case when a1.fgxp = 'XP' and a1.good = 1 then 1 
                             when a1.fgxp = 'FG' and a1.good = 1 and a1.dist <= 39 then 3
                             when a1.fgxp = 'FG' and a1.good = 1 and a1.dist >= 40 and dist <= 49 then 4
                             when a1.fgxp = 'FG' and a1.good = 1 and a1.dist >= 50 then 5
                             when a1.fgxp = 'FG' and a1.good = 0 then -1
                             else 0
                        end as pts
                        from fgxp as a1
                        join play as b1 on a1.pid = b1.pid) as a
                     join game as b on a.gid = b.gid
                     group by 1,2,3
                      ")
head(kicking)
```


```{r}
dbGetQuery(con = mydb,
           "select * from defense limit 10")
dbGetQuery(con = mydb,
           "select * from defense where tdd != tdret")
defense <- dbGetQuery(con = mydb,
                      "
                      select
                       a.gid
                      ,a.team
                      ,a.year
                      ,sum(a.pts) as fp
                      from
                      (select
                       a1.gid
                      ,a1.team
                      ,a1.year
                      ,a1.sck + 6*a1.tdret + 2*a1.ints + 2*a1.saf +2*a1.blk +2*a1.frcv +6*a1.tdd as pts
                      from defense as a1) as a
                      group by 1,2,3")
head(defense)
```

```{r}
dbGetQuery(con = mydb,
           "select * from game limit 10")

dbGetQuery(con = mydb,
           "select gid,seas,wk,h,ptsh,v,ptsv from game limit 20")
# need to change this to seas, wk, gid, team, pa
all_points <- dbGetQuery(con = mydb,
                         "select seas, wk, gid, h, ptsv as pa_h, v, ptsh as pa_v
                         from game")
head(all_points)

pa <-
  all_points %>%
  select(seas,wk,gid,h,pa_h) %>%
  rename(team = h, pa = pa_h) %>%
  union(.,all_points %>%
          select(seas,wk,gid,v,pa_v) %>%
          rename(team = v, pa = pa_v)
  ) %>%
  mutate(pts = ifelse(pa == 0, 5,
                      ifelse(pa >=1 & pa <=6, 4,
                             ifelse(pa >= 7 & pa <= 13,3,
                                    ifelse(pa >= 14 & pa <= 17,1,
                                           ifelse(pa >= 28 & pa <= 34, -1,
                                                  ifelse(pa >= 35 & pa <= 45, -3,
                                                         ifelse(pa >= 46, -5, 0))))))))

pa
# now yards against
# I think the way to do it is to look at yards by team, then give this value to their opponent

ty <- dbGetQuery(con = mydb,
                  "select
                    gid
                  , tid
                  , tname
                  , ry + py as ty
                  from team")
tya <- 
ty %>%
  group_by(gid) %>%
  mutate(tya = ifelse(row_number() == 1, lead(ty), lag(ty))) %>%
  select(gid,tname,tya) %>%
  mutate(fpts = ifelse(tya < 100, 5,
                        ifelse(tya >= 100 & tya <= 199, 3,
                               ifelse(tya >= 200 & tya <= 299, 2,
                                      ifelse(tya >= 350 & tya <= 399,-1,
                                             ifelse(tya >= 400 & tya <= 449, -3,
                                                    ifelse(tya >= 450 & tya <= 499,-5,
                                                           ifelse(tya >= 500 & tya <= 549, -6,
                                                                  ifelse(tya >= 550, -7,0)))))))))
head(tya)

total_defense <- 
  defense %>%
  select(gid,team,fp) %>%
  inner_join(pa %>% select(gid,team,pts),
             by = c("gid","team")) %>%
  inner_join(tya %>% select(-tya),
             by = c("gid","team" = "tname")) %>%
  ungroup() %>%
  mutate(points = fp + pts + fpts) %>%
  select(-fp,-pts,-fpts)
head(total_defense)
```

```{r}
coach <- dbGetQuery(con = mydb,
                    "select
                      gid
                    , seas
                    , wk
                    , h as coach
                    , case when (ptsh - ptsv) >= 25 then 3
                           when (ptsh - ptsv) between  20 and  24 then 1
                           when (ptsh - ptsv) between  15 and  19 then 1
                           when (ptsh - ptsv) between -19 and -15 then -1
                           when (ptsh - ptsv) between -24 and -20 then -1
                           when (ptsh - ptsv) <= -25 then -3 
                           else 0 end as pts
                    from game
                    union
                    select
                      gid
                    , seas
                    , wk
                    , v as coach
                    , case when (ptsv - ptsh) >= 25 then 3
                           when (ptsv - ptsh) between  20 and  24 then 1
                           when (ptsv - ptsh) between  15 and  19 then 1
                           when (ptsv - ptsh) between -19 and -15 then -1
                           when (ptsv - ptsh) between -24 and -20 then -1
                           when (ptsv - ptsh) <= -25 then -3 
                           else 0 end as pts
                    from game")
head(coach)
```

```{r}
head(offense4)
head(kicking)
head(total_defense)
head(coach)
```

```{r}
with(offense4,table(game))
offense5 <- offense4 %>%
  select(player,year,week,fp) %>%
  rename(points = fp)
head(offense5)
filter(offense5, player == 'TB-2300')
head(offense5)
```

```{r}
head(kicking)
```

```{r}
head(total_defense)
total_defense2 <- total_defense %>%
  left_join(.,
            dbGetQuery(con = mydb,
                       "select gid, seas as year, wk as week from game"),
            by = c("gid")) %>%
  mutate(player = paste0(team,"/DST")) %>%
  select(player,year,week,points)
head(total_defense2)
```

```{r}
head(coach)
coach2 <-
  coach %>%
  rename(year = seas,
         week = wk,
         points = pts) %>%
  mutate(player = paste0(coach,"/HC")) %>%
  select(player, year, week, points)
```

```{r}
points_week_data <- rbind(offense5,
                          kicking,
                          total_defense2,
                          coach2) %>%
  group_by(player,week,year) %>%
  summarise(points = sum(points)) %>%
  ungroup()
head(points_week_data)
points_week_data %>%
  filter(year >= 2009) %>%
  arrange(desc(points)) %>%
  slice(1:10)
save(points_week_data, file = "/home/john/stats_corner/points_week_data.Rda")
dbGetQuery(con = mydb,
           "select * from player where player = 'JH-2200'")
```


```{r}
# For fantasy purposes, only use data from 2010 onward
points_week_data_2010 <- filter(points_week_data, year >= 2010)
save(points_week_data_2010, file = "/home/john/stats_corner/points_week_data_2010.Rda")
```


```{r}
# Actually, we need this split by year so that we can transpose each individually. 
# Also need a non-game variable for each player to indicate draft or not. 
# First try to transpose
dbGetQuery(con = mydb,
           "select * from player where player = 'WW-0200'")
points_week_data_2010 %>%
  filter(year == 2010) %>%
  select(-year) %>%
  spread(.,
         key = week,
         value = points,
         fill = 0) #%>%
  spread(.,
         key = player,
         value = 

```







