baseURL = "http://www.statscorner.com"
languageCode = "en"
title = "Stats Corner"
theme = "hugo-nuo"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "disqus_shortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Google Analytics UA number
googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you likes to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
  
[[menu.main]]
  name = "Posts"
  weight = 10
  identifer = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Advanced Standings"
  weight = 20
  identifier = "advanced-standings"
  url = "http://ec2-54-213-112-234.us-west-2.compute.amazonaws.com:3838/stats-corner/advanced-standings/"

[[menu.main]]
  name = "Record Book"
  weight = 20
  identifier = "record-book"
  url = "http://ec2-54-213-112-234.us-west-2.compute.amazonaws.com:3838/stats-corner/record-book/"

[permalinks]
    post = "/:year/:month/:day/:slug/"


# Add your own params here
[params]
  author = "Ritchie Zhu"
  avatar = "/home/john/stats_corner/stats-corner-web/content/media/stats-corner-logo.png"
  seotitle = "Hugo Blog (SEO Version)"
  subtitle = ""
  description = "Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again."
  paginate = 10

  # Choose your social networks
  email = "stats.corner@gmail.com"
  github = "johnckane/stats-corner"
  #twitter = "twitter_username"
  #linkedin = "linkedin_username"
  #weibo = "weibo_username"
  #wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = "22596E34341DD1D17D6022C44647E587"