# Three data sources
# 1) Draft histtory X
# 2) ADP history  X
# 3) AA stats

## Draft history
load("/home/john/stats_corner/fantasy_football/draft_data.Rda")

# Columns needed for draft data
# lag_cost1,...,lag_cost6,lag_keeper1,lag_keeper6


# We want keeper data from all years, cost data only if non-keeper



draft_data_lag_cost <- 
  draft_data %>%
  filter(keeper == 0) %>%
  ungroup() %>%
  arrange(player_code,year) %>%
  group_by(player_code) %>%
  mutate(lag_cost1 = ifelse(lag(year,1) == year - 1,lag(adj_value,1), NA),
         lag_cost2 = ifelse(lag(year,1) == year - 2,
                       lag(adj_value,1),
                       ifelse(lag(year,2) == year - 2, 
                              lag(adj_value,2),
                              NA)),
         lag_cost3 = ifelse(lag(year,1) == year - 3, 
                       lag(adj_value,1),
                       ifelse(lag(year,2) == year - 3,
                              lag(adj_value,2),
                              ifelse(lag(year,3) == year - 3,
                                     lag(adj_value,3),
                                     NA))),
         lag_cost4 = ifelse(lag(year,1) == year - 4,
                       lag(adj_value,1),
                       ifelse(lag(year,2) == year - 4,
                              lag(adj_value,2),
                              ifelse(lag(year,3) == year - 4,
                                     lag(adj_value,3),
                                     ifelse(lag(year,4) == year -  4,
                                            lag(adj_value,4),
                                            NA)))),
         lag_cost5 = ifelse(lag(year,1) == year - 5,
                       lag(adj_value,1),
                       ifelse(lag(year,2) == year - 5,
                              lag(adj_value,2),
                              ifelse(lag(year,3) == year - 5,
                                     lag(adj_value,3),
                                     ifelse(lag(year,4) == year -  5,
                                            lag(adj_value,4),
                                            ifelse(lag(year,5) == year - 5,
                                                   lag(adj_value,5),
                                                   NA))))),
         lag_cost6 = ifelse(lag(year,1) == year - 6,
                            lag(adj_value,1),
                            ifelse(lag(year,2) == year - 6,
                                   lag(adj_value,2),
                                   ifelse(lag(year,3) == year - 6,
                                          lag(adj_value,3),
                                          ifelse(lag(year,4) == year -  6,
                                                 lag(adj_value,4),
                                                 ifelse(lag(year,5) == year - 6,
                                                        lag(adj_value,5),
                                                        ifelse(lag(year,6) == year - 6,
                                                               lag(adj_value,6),
                                                               NA)))))))
draft_data_lag_keeper <-
  draft_data %>%
  ungroup() %>%
  arrange(player_code,year) %>%
  group_by(player_code) %>%
  mutate(lag_keep1 = ifelse(lag(year,1) == year - 1,lag(keeper,1), NA),
         lag_keep2 = ifelse(lag(year,1) == year - 2,
                            lag(keeper,1),
                            ifelse(lag(year,2) == year - 2, 
                                   lag(keeper,2),
                                   NA)),
         lag_keep3 = ifelse(lag(year,1) == year - 3, 
                            lag(keeper,1),
                            ifelse(lag(year,2) == year - 3,
                                   lag(keeper,2),
                                   ifelse(lag(year,3) == year - 3,
                                          lag(keeper,3),
                                          NA))),
         lag_keep4 = ifelse(lag(year,1) == year - 4,
                            lag(keeper,1),
                            ifelse(lag(year,2) == year - 4,
                                   lag(keeper,2),
                                   ifelse(lag(year,3) == year - 4,
                                          lag(keeper,3),
                                          ifelse(lag(year,4) == year -  4,
                                                 lag(keeper,4),
                                                 NA)))),
         lag_keep5 = ifelse(lag(year,1) == year - 5,
                            lag(keeper,1),
                            ifelse(lag(year,2) == year - 5,
                                   lag(keeper,2),
                                   ifelse(lag(year,3) == year - 5,
                                          lag(keeper,3),
                                          ifelse(lag(year,4) == year -  5,
                                                 lag(keeper,4),
                                                 ifelse(lag(year,5) == year - 5,
                                                        lag(keeper,5),
                                                        NA))))),
         lag_keep6 = ifelse(lag(year,1) == year - 6,
                            lag(keeper,1),
                            ifelse(lag(year,2) == year - 6,
                                   lag(keeper,2),
                                   ifelse(lag(year,3) == year - 6,
                                          lag(keeper,3),
                                          ifelse(lag(year,4) == year -  6,
                                                 lag(keeper,4),
                                                 ifelse(lag(year,5) == year - 6,
                                                        lag(keeper,5),
                                                        ifelse(lag(year,6) == year - 6,
                                                               lag(keeper,6),
                                                               NA)))))))

lag_draft_data <- 
  draft_data_lag_keeper %>%
  ungroup() %>%
  left_join(.,
            draft_data_lag_cost %>% 
              ungroup() %>% 
              select(year,player_code,lag_cost1,lag_cost2,lag_cost3,lag_cost4,lag_cost5,lag_cost6), 
            by = c("player_code","year"))

### ADP history
load("/home/john/stats_corner/fantasy_football/coded_adp_data_2010_2016.Rda")
str(coded_adp_data2)
coded_adp_data2$pick <- as.numeric(coded_adp_data2$pick)
head(adp_data)
# Want to get lag values of adp overall and by position
adp_data2 <-
  coded_adp_data2 %>%
  arrange(year,pick) %>%
  group_by(year) %>%
  mutate(overall_adp = row_number()) %>%
  ungroup() %>%
  arrange(year,pos,pick) %>%
  group_by(year,pos) %>%
  mutate(position_adp = row_number())


# Calculate the lags...
adp_data3 <-
  adp_data2 %>%
  ungroup() %>%
  arrange(player_code,year) %>%
  group_by(player_code) %>%
  mutate(lag_oa_adp1 = ifelse(lag(year,1) == year - 1,lag(overall_adp,1), NA),
         lag_oa_adp2 = ifelse(lag(year,1) == year - 2,
                            lag(overall_adp,1),
                            ifelse(lag(year,2) == year - 2, 
                                   lag(overall_adp,2),
                                   NA)),
         lag_oa_adp3 = ifelse(lag(year,1) == year - 3, 
                            lag(overall_adp,1),
                            ifelse(lag(year,2) == year - 3,
                                   lag(overall_adp,2),
                                   ifelse(lag(year,3) == year - 3,
                                          lag(overall_adp,3),
                                          NA))),
         lag_oa_adp4 = ifelse(lag(year,1) == year - 4,
                            lag(overall_adp,1),
                            ifelse(lag(year,2) == year - 4,
                                   lag(overall_adp,2),
                                   ifelse(lag(year,3) == year - 4,
                                          lag(overall_adp,3),
                                          ifelse(lag(year,4) == year -  4,
                                                 lag(overall_adp,4),
                                                 NA)))),
         lag_oa_adp5 = ifelse(lag(year,1) == year - 5,
                            lag(overall_adp,1),
                            ifelse(lag(year,2) == year - 5,
                                   lag(overall_adp,2),
                                   ifelse(lag(year,3) == year - 5,
                                          lag(overall_adp,3),
                                          ifelse(lag(year,4) == year -  5,
                                                 lag(overall_adp,4),
                                                 ifelse(lag(year,5) == year - 5,
                                                        lag(overall_adp,5),
                                                        NA))))),
         lag_oa_adp6 = ifelse(lag(year,1) == year - 6,
                            lag(overall_adp,1),
                            ifelse(lag(year,2) == year - 6,
                                   lag(overall_adp,2),
                                   ifelse(lag(year,3) == year - 6,
                                          lag(overall_adp,3),
                                          ifelse(lag(year,4) == year -  6,
                                                 lag(overall_adp,4),
                                                 ifelse(lag(year,5) == year - 6,
                                                        lag(overall_adp,5),
                                                        ifelse(lag(year,6) == year - 6,
                                                               lag(overall_adp,6),
                                                               NA)))))),
         lag_oa_adp7 = ifelse(lag(year,1) == year - 7,
                              lag(overall_adp,1),
                              ifelse(lag(year,2) == year - 7,
                                     lag(overall_adp,2),
                                     ifelse(lag(year,3) == year - 7,
                                            lag(overall_adp,3),
                                            ifelse(lag(year,4) == year -  7,
                                                   lag(overall_adp,4),
                                                   ifelse(lag(year,5) == year - 7,
                                                          lag(overall_adp,5),
                                                          ifelse(lag(year,6) == year - 7,
                                                                 lag(overall_adp,6),
                                                                 ifelse(lag(year,7) == year - 7,
                                                                        lag(overall_adp,7),
                                                                        NA))))))),
         lag_oa_adp8 = ifelse(lag(year,1) == year - 8,
                              lag(overall_adp,1),
                              ifelse(lag(year,2) == year - 8,
                                     lag(overall_adp,2),
                                     ifelse(lag(year,3) == year - 8,
                                            lag(overall_adp,3),
                                            ifelse(lag(year,4) == year -  8,
                                                   lag(overall_adp,4),
                                                   ifelse(lag(year,5) == year - 8,
                                                          lag(overall_adp,5),
                                                          ifelse(lag(year,6) == year - 8,
                                                                 lag(overall_adp,6),
                                                                 ifelse(lag(year,7) == year - 8,
                                                                        lag(overall_adp,7),
                                                                        ifelse(lag(year,8) == year - 8,
                                                                               lag(overall_adp,8),
                                                                               NA)))))))),
         lag_oa_adp9 = ifelse(lag(year,1) == year - 9,
                              lag(overall_adp,1),
                              ifelse(lag(year,2) == year - 9,
                                     lag(overall_adp,2),
                                     ifelse(lag(year,3) == year - 9,
                                            lag(overall_adp,3),
                                            ifelse(lag(year,4) == year -  9,
                                                   lag(overall_adp,4),
                                                   ifelse(lag(year,5) == year - 9,
                                                          lag(overall_adp,5),
                                                          ifelse(lag(year,6) == year - 9,
                                                                 lag(overall_adp,6),
                                                                 ifelse(lag(year,7) == year - 9,
                                                                        lag(overall_adp,7),
                                                                        ifelse(lag(year,8) == year - 9,
                                                                               lag(overall_adp,8),
                                                                               ifelse(lag(year,9) == year - 9,
                                                                                      lag(overall_adp,9),
                                                                                      NA))))))))),
         lag_oa_adp10 = ifelse(lag(year,1) == year - 10,
                               lag(overall_adp,1),
                               ifelse(lag(year,2) == year - 10,
                                      lag(overall_adp,2),
                                      ifelse(lag(year,3) == year - 10,
                                             lag(overall_adp,3),
                                             ifelse(lag(year,4) == year -  10,
                                                    lag(overall_adp,4),
                                                    ifelse(lag(year,5) == year - 10,
                                                           lag(overall_adp,5),
                                                           ifelse(lag(year,6) == year - 10,
                                                                  lag(overall_adp,6),
                                                                  ifelse(lag(year,7) == year - 10,
                                                                         lag(overall_adp,7),
                                                                         ifelse(lag(year,8) == year - 10,
                                                                                lag(overall_adp,8),
                                                                                ifelse(lag(year,9) == year - 10,
                                                                                       lag(overall_adp,9),
                                                                                       ifelse(lag(year,10) == year -10,
                                                                                              lag(overall_adp,10),
                                                                                              NA))))))))))) %>%
  mutate(lag_pos_adp1 = ifelse(lag(year,1) == year - 1,lag(position_adp,1), NA),
                lag_pos_adp2 = ifelse(lag(year,1) == year - 2,
                                     lag(position_adp,1),
                                     ifelse(lag(year,2) == year - 2, 
                                            lag(position_adp,2),
                                            NA)),
                lag_pos_adp3 = ifelse(lag(year,1) == year - 3, 
                                     lag(position_adp,1),
                                     ifelse(lag(year,2) == year - 3,
                                            lag(position_adp,2),
                                            ifelse(lag(year,3) == year - 3,
                                                   lag(position_adp,3),
                                                   NA))),
                lag_pos_adp4 = ifelse(lag(year,1) == year - 4,
                                     lag(position_adp,1),
                                     ifelse(lag(year,2) == year - 4,
                                            lag(position_adp,2),
                                            ifelse(lag(year,3) == year - 4,
                                                   lag(position_adp,3),
                                                   ifelse(lag(year,4) == year -  4,
                                                          lag(position_adp,4),
                                                          NA)))),
                lag_pos_adp5 = ifelse(lag(year,1) == year - 5,
                                     lag(position_adp,1),
                                     ifelse(lag(year,2) == year - 5,
                                            lag(position_adp,2),
                                            ifelse(lag(year,3) == year - 5,
                                                   lag(position_adp,3),
                                                   ifelse(lag(year,4) == year -  5,
                                                          lag(position_adp,4),
                                                          ifelse(lag(year,5) == year - 5,
                                                                 lag(position_adp,5),
                                                                 NA))))),
                lag_pos_adp6 = ifelse(lag(year,1) == year - 6,
                                     lag(position_adp,1),
                                     ifelse(lag(year,2) == year - 6,
                                            lag(position_adp,2),
                                            ifelse(lag(year,3) == year - 6,
                                                   lag(position_adp,3),
                                                   ifelse(lag(year,4) == year -  6,
                                                          lag(position_adp,4),
                                                          ifelse(lag(year,5) == year - 6,
                                                                 lag(position_adp,5),
                                                                 ifelse(lag(year,6) == year - 6,
                                                                        lag(position_adp,6),
                                                                        NA)))))),
                lag_pos_adp7 = ifelse(lag(year,1) == year - 7,
                                     lag(position_adp,1),
                                     ifelse(lag(year,2) == year - 7,
                                            lag(position_adp,2),
                                            ifelse(lag(year,3) == year - 7,
                                                   lag(position_adp,3),
                                                   ifelse(lag(year,4) == year -  7,
                                                          lag(position_adp,4),
                                                          ifelse(lag(year,5) == year - 7,
                                                                 lag(position_adp,5),
                                                                 ifelse(lag(year,6) == year - 7,
                                                                        lag(position_adp,6),
                                                                        ifelse(lag(year,7) == year - 7,
                                                                               lag(position_adp,7),
                                                                               NA))))))),
                lag_pos_adp8 = ifelse(lag(year,1) == year - 8,
                                     lag(position_adp,1),
                                     ifelse(lag(year,2) == year - 8,
                                            lag(position_adp,2),
                                            ifelse(lag(year,3) == year - 8,
                                                   lag(position_adp,3),
                                                   ifelse(lag(year,4) == year -  8,
                                                          lag(position_adp,4),
                                                          ifelse(lag(year,5) == year - 8,
                                                                 lag(position_adp,5),
                                                                 ifelse(lag(year,6) == year - 8,
                                                                        lag(position_adp,6),
                                                                        ifelse(lag(year,7) == year - 8,
                                                                               lag(position_adp,7),
                                                                               ifelse(lag(year,8) == year - 8,
                                                                                      lag(position_adp,8),
                                                                                      NA)))))))),
                lag_pos_adp9 = ifelse(lag(year,1) == year - 9,
                                     lag(position_adp,1),
                                     ifelse(lag(year,2) == year - 9,
                                            lag(position_adp,2),
                                            ifelse(lag(year,3) == year - 9,
                                                   lag(position_adp,3),
                                                   ifelse(lag(year,4) == year -  9,
                                                          lag(position_adp,4),
                                                          ifelse(lag(year,5) == year - 9,
                                                                 lag(position_adp,5),
                                                                 ifelse(lag(year,6) == year - 9,
                                                                        lag(position_adp,6),
                                                                        ifelse(lag(year,7) == year - 9,
                                                                               lag(position_adp,7),
                                                                               ifelse(lag(year,8) == year - 9,
                                                                                      lag(position_adp,8),
                                                                                      ifelse(lag(year,9) == year - 9,
                                                                                             lag(position_adp,9),
                                                                                             NA))))))))),
                lag_pos_adp10 = ifelse(lag(year,1) == year - 10,
                                      lag(position_adp,1),
                                      ifelse(lag(year,2) == year - 10,
                                             lag(position_adp,2),
                                             ifelse(lag(year,3) == year - 10,
                                                    lag(position_adp,3),
                                                    ifelse(lag(year,4) == year -  10,
                                                           lag(position_adp,4),
                                                           ifelse(lag(year,5) == year - 10,
                                                                  lag(position_adp,5),
                                                                  ifelse(lag(year,6) == year - 10,
                                                                         lag(position_adp,6),
                                                                         ifelse(lag(year,7) == year - 10,
                                                                                lag(position_adp,7),
                                                                                ifelse(lag(year,8) == year - 10,
                                                                                       lag(position_adp,8),
                                                                                       ifelse(lag(year,9) == year - 10,
                                                                                              lag(position_adp,9),
                                                                                              ifelse(lag(year,10) == year -10,
                                                                                                     lag(position_adp,10),
                                                                                                     NA)))))))))))

# point week data
load("/home/john/stats_corner/fantasy_football/points_week_data.Rda")
points_week_data %<>%
  filter(week <= 17) 

pwd_total <-
  points_week_data %>%
  group_by(player,year) %>%
  summarise(games = n(),
            ppg = mean(points),
            ttl = sum(points))

# Can go all the way up to lag 17
pwd_total_wlag <-
  pwd_total %>%
  ungroup() %>%
  arrange(player,year) %>%
  group_by(player) %>%
  mutate(lag_ppg1 = ifelse(lag(year,1) == year - 1,lag(ppg,1), NA),
         lag_ppg2 = ifelse(lag(year,1) == year - 2,
                              lag(ppg,1),
                              ifelse(lag(year,2) == year - 2, 
                                     lag(ppg,2),
                                     NA)),
         lag_ppg3 = ifelse(lag(year,1) == year - 3,
                          lag(ppg,1),
                          ifelse(lag(year,2) == year - 3,
                                 lag(ppg,2),
                                 ifelse(lag(year,3) == year -3,
                                        lag(ppg,3),
                                        NA))),
         lag_ppg4 = ifelse(lag(year,1) == year - 4,
                           lag(ppg,1),
                           ifelse(lag(year,2) == year - 4,
                                  lag(ppg,2),
                                  ifelse(lag(year,3) == year - 4,
                                         lag(ppg,3),
                                         ifelse(lag(year,4) == year - 4,
                                                lag(ppg,4),
                                                NA)))),
         lag_ppg5 = ifelse(lag(year,1) == year - 5,
                           lag(ppg,1),
                           ifelse(lag(year,2) == year - 5,
                                  lag(ppg,2),
                                  ifelse(lag(year,3) == year - 5,
                                         lag(ppg,3),
                                         ifelse(lag(year,4) == year - 5,
                                                lag(ppg,4),
                                                ifelse(lag(year,5) == year - 5,
                                                       lag(ppg,5),
                                                       NA))))),
         lag_ppg6 = ifelse(lag(year,1) == year - 6,
                           lag(ppg,1),
                           ifelse(lag(year,2) == year - 6,
                                  lag(ppg,2),
                                  ifelse(lag(year,3) == year - 6,
                                         lag(ppg,3),
                                         ifelse(lag(year,4) == year - 6,
                                                lag(ppg,4),
                                                ifelse(lag(year,5) == year - 6,
                                                       lag(ppg,5),
                                                       ifelse(lag(year,6) == year - 6,
                                                              lag(ppg,6),
                                                              NA)))))),
         lag_ppg7 = ifelse(lag(year,1) == year - 7,
                           lag(ppg,1),
                           ifelse(lag(year,2) == year - 7,
                                  lag(ppg,2),
                                  ifelse(lag(year,3) == year - 7,
                                         lag(ppg,3),
                                         ifelse(lag(year,4) == year - 7,
                                                lag(ppg,4),
                                                ifelse(lag(year,5) == year - 7,
                                                       lag(ppg,5),
                                                       ifelse(lag(year,6) == year - 7,
                                                              lag(ppg,6),
                                                              ifelse(lag(year,7) == year -7,
                                                                     lag(ppg,7),
                                                                     NA))))))),
         lag_ppg8 = ifelse(lag(year,1) == year - 8,
                           lag(ppg,1),
                           ifelse(lag(year,2) == year - 8,
                                  lag(ppg,2),
                                  ifelse(lag(year,3) == year - 8,
                                         lag(ppg,3),
                                         ifelse(lag(year,4) == year - 8,
                                                lag(ppg,4),
                                                ifelse(lag(year,5) == year - 8,
                                                       lag(ppg,5),
                                                       ifelse(lag(year,6) == year - 8,
                                                              lag(ppg,6),
                                                              ifelse(lag(year,7) == year - 8,
                                                                     lag(ppg,7),
                                                                     ifelse(lag(year,8) == year - 8,
                                                                            lag(ppg,8),
                                                                            NA)))))))),
         lag_ppg9 = ifelse(lag(year,1) == year - 9,
                           lag(ppg,1),
                           ifelse(lag(year,2) == year - 9,
                                  lag(ppg,2),
                                  ifelse(lag(year,3) == year - 9,
                                         lag(ppg,3),
                                         ifelse(lag(year,4) == year - 9,
                                                lag(ppg,4),
                                                ifelse(lag(year,5) == year - 9,
                                                       lag(ppg,5),
                                                       ifelse(lag(year,6) == year - 9,
                                                              lag(ppg,6),
                                                              ifelse(lag(year,7) == year - 9,
                                                                     lag(ppg,7),
                                                                     ifelse(lag(year,8) == year - 9,
                                                                            lag(ppg,8),
                                                                            ifelse(lag(year,9) == year - 9,
                                                                                   lag(ppg,9),
                                                                                   NA))))))))),
         lag_ppg10 = ifelse(lag(year,1) == year - 10,
                           lag(ppg,1),
                           ifelse(lag(year,2) == year - 10,
                                  lag(ppg,2),
                                  ifelse(lag(year,3) == year - 10,
                                         lag(ppg,3),
                                         ifelse(lag(year,4) == year - 10,
                                                lag(ppg,4),
                                                ifelse(lag(year,5) == year - 10,
                                                       lag(ppg,5),
                                                       ifelse(lag(year,6) == year - 10,
                                                              lag(ppg,6),
                                                              ifelse(lag(year,7) == year - 10,
                                                                     lag(ppg,7),
                                                                     ifelse(lag(year,8) == year - 10,
                                                                            lag(ppg,8),
                                                                            ifelse(lag(year,9) == year - 10,
                                                                                   lag(ppg,9),
                                                                                   ifelse(lag(year, 10) == year - 10,
                                                                                          lag(ppg,10),
                                                                                          NA))))))))))
  ) %>%
  mutate(lag_ttl1 = ifelse(lag(year,1) == year - 1,lag(ttl,1), NA),
         lag_ttl2 = ifelse(lag(year,1) == year - 2,
                           lag(ttl,1),
                           ifelse(lag(year,2) == year - 2, 
                                  lag(ttl,2),
                                  NA)),
         lag_ttl3 = ifelse(lag(year,1) == year - 3,
                           lag(ttl,1),
                           ifelse(lag(year,2) == year - 3,
                                  lag(ttl,2),
                                  ifelse(lag(year,3) == year -3,
                                         lag(ttl,3),
                                         NA))),
         lag_ttl4 = ifelse(lag(year,1) == year - 4,
                           lag(ttl,1),
                           ifelse(lag(year,2) == year - 4,
                                  lag(ttl,2),
                                  ifelse(lag(year,3) == year - 4,
                                         lag(ttl,3),
                                         ifelse(lag(year,4) == year - 4,
                                                lag(ttl,4),
                                                NA)))),
         lag_ttl5 = ifelse(lag(year,1) == year - 5,
                           lag(ttl,1),
                           ifelse(lag(year,2) == year - 5,
                                  lag(ttl,2),
                                  ifelse(lag(year,3) == year - 5,
                                         lag(ttl,3),
                                         ifelse(lag(year,4) == year - 5,
                                                lag(ttl,4),
                                                ifelse(lag(year,5) == year - 5,
                                                       lag(ttl,5),
                                                       NA))))),
         lag_ttl6 = ifelse(lag(year,1) == year - 6,
                           lag(ttl,1),
                           ifelse(lag(year,2) == year - 6,
                                  lag(ttl,2),
                                  ifelse(lag(year,3) == year - 6,
                                         lag(ttl,3),
                                         ifelse(lag(year,4) == year - 6,
                                                lag(ttl,4),
                                                ifelse(lag(year,5) == year - 6,
                                                       lag(ttl,5),
                                                       ifelse(lag(year,6) == year - 6,
                                                              lag(ttl,6),
                                                              NA)))))),
         lag_ttl7 = ifelse(lag(year,1) == year - 7,
                           lag(ttl,1),
                           ifelse(lag(year,2) == year - 7,
                                  lag(ttl,2),
                                  ifelse(lag(year,3) == year - 7,
                                         lag(ttl,3),
                                         ifelse(lag(year,4) == year - 7,
                                                lag(ttl,4),
                                                ifelse(lag(year,5) == year - 7,
                                                       lag(ttl,5),
                                                       ifelse(lag(year,6) == year - 7,
                                                              lag(ttl,6),
                                                              ifelse(lag(year,7) == year -7,
                                                                     lag(ttl,7),
                                                                     NA))))))),
         lag_ttl8 = ifelse(lag(year,1) == year - 8,
                           lag(ttl,1),
                           ifelse(lag(year,2) == year - 8,
                                  lag(ttl,2),
                                  ifelse(lag(year,3) == year - 8,
                                         lag(ttl,3),
                                         ifelse(lag(year,4) == year - 8,
                                                lag(ttl,4),
                                                ifelse(lag(year,5) == year - 8,
                                                       lag(ttl,5),
                                                       ifelse(lag(year,6) == year - 8,
                                                              lag(ttl,6),
                                                              ifelse(lag(year,7) == year - 8,
                                                                     lag(ttl,7),
                                                                     ifelse(lag(year,8) == year - 8,
                                                                            lag(ttl,8),
                                                                            NA)))))))),
         lag_ttl9 = ifelse(lag(year,1) == year - 9,
                           lag(ttl,1),
                           ifelse(lag(year,2) == year - 9,
                                  lag(ttl,2),
                                  ifelse(lag(year,3) == year - 9,
                                         lag(ttl,3),
                                         ifelse(lag(year,4) == year - 9,
                                                lag(ttl,4),
                                                ifelse(lag(year,5) == year - 9,
                                                       lag(ttl,5),
                                                       ifelse(lag(year,6) == year - 9,
                                                              lag(ttl,6),
                                                              ifelse(lag(year,7) == year - 9,
                                                                     lag(ttl,7),
                                                                     ifelse(lag(year,8) == year - 9,
                                                                            lag(ttl,8),
                                                                            ifelse(lag(year,9) == year - 9,
                                                                                   lag(ttl,9),
                                                                                   NA))))))))),
         lag_ttl10 = ifelse(lag(year,1) == year - 10,
                           lag(ttl,1),
                           ifelse(lag(year,2) == year - 10,
                                  lag(ttl,2),
                                  ifelse(lag(year,3) == year - 10,
                                         lag(ttl,3),
                                         ifelse(lag(year,4) == year - 10,
                                                lag(ttl,4),
                                                ifelse(lag(year,5) == year - 10,
                                                       lag(ttl,5),
                                                       ifelse(lag(year,6) == year - 10,
                                                              lag(ttl,6),
                                                              ifelse(lag(year,7) == year - 10,
                                                                     lag(ttl,7),
                                                                     ifelse(lag(year,8) == year - 10,
                                                                            lag(ttl,8),
                                                                            ifelse(lag(year,9) == year - 10,
                                                                                   lag(ttl,9),
                                                                                   ifelse(lag(year, 10) == year - 10,
                                                                                          lag(ttl,10),
                                                                                          NA))))))))))
  )

# Join
draft_and_points <-
  lag_draft_data %>%
  left_join(pwd_total_wlag,by = c("year","player_code" = "player"))

na_count <-sapply(draft_and_points, function(y) sum(length(which(is.na(y)))))
na_count
table(draft_and_points$pos)
1356-101-84

## Need player data.
library(RMySQL)
library(tidyverse)
mydb = dbConnect(MySQL(), user='root', password='cz14F4b12', dbname='armchair_analysis', host='localhost')

player_info <- dbGetQuery(con = mydb,
           "select player, yob, start from player")

## Now bring all data together, calc new vars and drop unneeded vars
#colnames(adp_data3)
training_data <- 
  lag_draft_data %>%
  left_join(adp_data3, by = c("year","player_code" = "player_code")) %>%
  left_join(pwd_total_wlag, by = c("year","player_code" = "player")) %>%
  left_join(player_info, by = c("player_code" = "player")) %>%
  mutate(age = year - yob,
         experience = year-start) %>%
  rename(player = player.x,
         pick = pick.x,
         team = team.x,
         pos = pos.x) %>%
  select(-pick.y,-pos.y,-team.y,-player.y,-games,-first_name,-last_name,-ppg,-ttl,-yob,-start,-times_drafted)
training_data2017 <- training_data
save(training_data, file = "/home/john/stats_corner/2017/predict-cost-model/training_data2017.Rda")
